
services:
  skelapp:
    container_name: skelapp
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./skelapp:/skelapp
      - ./data:/data
      - skel-db:/data/postgresql/data
      - skel-web-static:/data/web/static
      - skel-web-media:/data/web/media
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - skelpsql
    networks:
      - skel-network

  skelpsql:
    container_name: skelpsql
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - skel-db:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    networks:
      - skel-network

  skelnginx:
    container_name: skelnginx
    image: nginx:1.28-alpine
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - skel-web-static:/data/web/static
      - skel-web-media:/data/web/media
    depends_on:
      - skelapp
    networks:
      - skel-network

networks:
  skel-network:
    driver: bridge

volumes:
  skel-web-static:
  skel-web-media:
  skel-db:
