
services:

  djangoapp:
    container_name: djangoapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - pgsql
    networks:
      - docker-network

  pgsql:
    container_name: pgsql
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    networks:
      - docker-network

  nginx:
    image: nginx:1.28-alpine
    ports:
      - 8001:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - djangoapp
    networks:
      - docker-network

networks:

  docker-network:
    driver: bridge
